name: Test

on:
    push:
        branches: [ rewrite ]
    pull_request:
        branches: [ rewrite ]

    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [13.x, 14.x, 15.x, 16.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - run: yarn install
            - run: yarn build build
            - run: yarn test
